server:
    port: 8081

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:30000/sales}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:command_user}
    password: ${SPRING_DATASOURCE_PASSWORD:FNQXvAzNCew6YMkdnDAp79bpT4ub}
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: device-consumer-group

message:
  topic:
    createDevice: create-device
    updateDevice: update-device
    deleteDevice: delete-device